# Generated by Django 4.0.6 on 2022-08-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_remove_section_start_date_event_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=24, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='telegram_id',
            field=models.CharField(max_length=24, unique=True, verbose_name='Telegram ID'),
        ),
    ]
