# Generated by Django 4.0.6 on 2022-08-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_alter_visitor_phone_number_alter_visitor_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='speaker',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_questions', to='meetups.visitor', verbose_name='Спикер'),
            preserve_default=False,
        ),
    ]
